replicaCount: 1

image:
  repository: ghcr.io/bcgov/cheque-verification-frontend
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 3000

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

# Config for the frontend (API endpoints, etc.)
config:
  API_BASE_URL: "http://cheque-verification-backend:80"
