name: Build and Deploy to Test

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build frontend image
      - name: Extract metadata for frontend
        id: meta-frontend
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-frontend

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ steps.meta-frontend.outputs.tags }}
          labels: ${{ steps.meta-frontend.outputs.labels }}

      # Build backend image
      - name: Extract metadata for backend
        id: meta-backend
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-backend

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ steps.meta-backend.outputs.tags }}
          labels: ${{ steps.meta-backend.outputs.labels }}

      # Build api image
      - name: Extract metadata for api
        id: meta-api
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-api

      - name: Build and push api image
        uses: docker/build-push-action@v5
        with:
          context: ./api
          file: ./api/Dockerfile
          push: true
          tags: ${{ steps.meta-api.outputs.tags }}
          labels: ${{ steps.meta-api.outputs.labels }}

    outputs:
      frontend_image: ${{ steps.meta-frontend.outputs.tags }}
      backend_image: ${{ steps.meta-backend.outputs.tags }}
      api_image: ${{ steps.meta-api.outputs.tags }}

  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Install oc
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: 4

      # Deploy to Silver (frontend and backend)
      - name: Authenticate with OpenShift Silver
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_SILVER }}
          namespace: ${{ secrets.OPENSHIFT_TEST_NAMESPACE_SILVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN_SILVER }}

      - name: Deploy frontend and backend with Helm
        run: |
          helm upgrade --install cheque-verification-frontend ./helm/cheque-verification-frontend \
            --namespace ${{ secrets.OPENSHIFT_TEST_NAMESPACE_SILVER }} \
            --set image.repository=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-frontend \
            --set image.tag=${{ needs.build_and_push.outputs.frontend_image }}

          helm upgrade --install cheque-verification-backend ./helm/cheque-verification-backend \
            --namespace ${{ secrets.OPENSHIFT_TEST_NAMESPACE_SILVER }} \
            --set image.repository=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-backend \
            --set image.tag=${{ needs.build_and_push.outputs.backend_image }}

      - name: Trigger OpenShift Rollout for Silver
        run: |
          oc rollout restart deployment/cheque-verification-frontend
          oc rollout restart deployment/cheque-verification-backend

      # Deploy to Emerald (api)
      - name: Authenticate with OpenShift Emerald
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_EMERALD }}
          namespace: ${{ secrets.OPENSHIFT_TEST_NAMESPACE_EMERALD }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN_EMERALD }}

      - name: Deploy api with Helm
        run: |
          helm upgrade --install cheque-verification-api ./helm/cheque-verification-api \
            --namespace ${{ secrets.OPENSHIFT_TEST_NAMESPACE_CLUSTER_B }} \
            --set image.repository=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-api \
            --set image.tag=${{ needs.build_and_push.outputs.api_image }}

      - name: Trigger OpenShift Rollout for Cluster B
        run: |
          oc rollout restart deployment/cheque-verification-api
